CREATE TABLE caller
(
    caller_id NUMBER GENERATED BY DEFAULT AS IDENTITY
    , first_name VARCHAR2(50)
    , last_name VARCHAR2(50)
    , created TIMESTAMP
    , modified TIMESTAMP
    , PRIMARY KEY(caller_id)
);
CREATE TABLE responder
(
    responder_id NUMBER GENERATED BY DEFAULT AS IDENTITY
    , first_name VARCHAR2(50) NOT NULL
    , last_name VARCHAR2(50) NOT NULL
    , created TIMESTAMP
    , modified TIMESTAMP
    , PRIMARY KEY(responder_id)
);
CREATE TABLE call
(
    call_id NUMBER GENERATED BY DEFAULT AS IDENTITY
    , caller_id NUMBER
    , responder_id NUMBER
    , created TIMESTAMP
    , modified TIMESTAMP
    , CONSTRAINT fk_caller FOREIGN KEY (caller_id) REFERENCES caller(caller_id)
    , CONSTRAINT fk_responder FOREIGN KEY (responder_id) REFERENCES responder(responder_id)
    , PRIMARY KEY(call_id)
);
